version: '3.4'

services:
  es01:
    build: 
      context: ./elasticsearch/.
      args:
        ES_VERSION: ${ES_VERSION}
        S3_ACCESS_KEY: ${S3_ACCESS_KEY}
        S3_SECRET_KEY: ${S3_SECRET_KEY}
        S3_REPOSITORY_CLIENT_NAME: ${S3_REPOSITORY_CLIENT_NAME}
    container_name: elasticsearch_${ES_VERSION}
    environment:
      - "discovery.type=single-node"
      - ELASTIC_USERNAME=${ES_USERNAME}
      - ELASTIC_PASSWORD=${ES_PASSWORD}
      - xpack.security.enabled=true
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
      - "9300:9300"
    restart: always
    volumes:
      - ./elasticsearch/data:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:${ES_VERSION}
    container_name: kibana_${ES_VERSION}
    environment:
      - ELASTICSEARCH_URL="http://${ES_HOST}:${ES_PORT}"
      - ELASTICSEARCH_HOSTS="http://${ES_HOST}:${ES_PORT}"
      - ELASTICSEARCH_USERNAME=${ES_USERNAME}
      - ELASTICSEARCH_PASSWORD=${ES_PASSWORD}
      - xpack.security.enabled=true
    links:
      - es01
    ports:
      - "5601:5601"
    restart: always
    depends_on:
      - es01

networks:
  elastic:
    driver: bridge